version: 1
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    stream  : ext://sys.stdout
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
loggers:
  root: 
    handlers: [console]
    level: INFO
  pybin.main:
    level: DEBUG